require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FilmsController do

  context "on POST to #create" do
    
    context "when valid" do
      
      before do
        @film = Factory.build(:film, :title => 'abc')        
      end
      
      it "should save a film" do
        @film.save.should be_true
      end

      it "should mock save a film through the controller" do
        Film.stubs(:new).with(@film.attributes).returns(@film)
        @film.expects(:save).returns(true)
        post :create, :film => @film.attributes      
      end

      it "should have a title set to 'abc'" do
        @film.title.should == "abc"
      end
    end

    context "when invalid" do
      
      before do
        @film = Factory.build(:film, :rating => -1)        
      end
      
      it "should not save a film" do
        @film.save.should be_false
      end
    end
  end
end
